### ISSUE TITLE
Exception in browser using `npm start`

### ISSUE THREAD

**Issue by SethDavenport** [rangle/angular2-redux-starter#13]
EXCEPTION: RangeError: Maximum call stack size exceededt.logError 
@ browser_adapter.js:76t.logGroup 
@ browser_adapter.js:86e.call 
@ exception_handler.js:56(anonymous function) 
@ application_ref.js:183e._notifyOnError 
@ ng_zone.js:430r.StringMapWrapper.merge.onError 
@ ng_zone.js:325r.run 
@ angular2-polyfills.js:141(anonymous function) 
@ ng_zone.js:343(anonymous function) 
@ angular2-polyfills.js:111D 
@ angular2-polyfills.js:1511I 
@ angular2-polyfills.js:1523T 
@ angular2-polyfills.js:1494(anonymous function) 
@ angular2-polyfills.js:243n 
@ ng_zone.js:383r.run 
@ angular2-polyfills.js:138(anonymous function) 
@ ng_zone.js:343(anonymous function) 
@ angular2-polyfills.js:111d 
@ angular2-polyfills.js:1305

browser_adapter.js:76STACKTRACE:t.logError 
@ browser_adapter.js:76e.call 
@ exception_handler.js:58(anonymous function) 
@ application_ref.js:183e._notifyOnError 
@ ng_zone.js:430r.StringMapWrapper.merge.onError 
@ ng_zone.js:325r.run 
@ angular2-polyfills.js:141(anonymous function) 
@ ng_zone.js:343(anonymous function) 
@ angular2-polyfills.js:111D 
@ angular2-polyfills.js:1511I 
@ angular2-polyfills.js:1523T 
@ angular2-polyfills.js:1494(anonymous function) 
@ angular2-polyfills.js:243n 
@ ng_zone.js:383r.run 
@ angular2-polyfills.js:138(anonymous function) 
@ ng_zone.js:343(anonymous function) 
@ angular2-polyfills.js:111d 
@ angular2-polyfills.js:1305
browser_adapter.js:76RangeError: Maximum call stack size exceeded
    at e._instantiate (http://localhost:3000/vendor.2fe36c3e0de211cbe176.bundle.js:1:27375)
    at e._instantiateProvider (http://localhost:3000/vendor.2fe36c3e0de211cbe176.bundle.js:1:25339)
    at e._new (http://localhost:3000/vendor.2fe36c3e0de211cbe176.bundle.js:1:25068)
    at e.instantiateProvider (http://localhost:3000/vendor.2fe36c3e0de211cbe176.bundle.js:1:20485)
    at e.init (http://localhost:3000/vendor.2fe36c3e0de211cbe176.bundle.js:8:6191)
    at new e (http://localhost:3000/vendor.2fe36c3e0de211cbe176.bundle.js:7:31212)
    at viewFactory_t0 (viewFactory_t:197:16)
    at viewFactory_t0 (viewFactory_t:199:1)
    at viewFactory_t0 (viewFactory_t:199:1)
    at viewFactory_t0 (viewFactory_t:199:1)

-----async gap-----
Error
    at r (http://localhost:3000/vendor.2fe36c3e0de211cbe176.bundle.js:52:7040)
    at r.fork (http://localhost:3000/vendor.2fe36c3e0de211cbe176.bundle.js:52:7966)
    at r.bind (http://localhost:3000/vendor.2fe36c3e0de211cbe176.bundle.js:45:1686)
    at r (http://localhost:3000/vendor.2fe36c3e0de211cbe176.bundle.js:45:13629)
    at W.e.(anonymous function) [as then] (http://localhost:3000/vendor.2fe36c3e0de211cbe176.bundle.js:45:13846)
    at t.loadAsRoot (http://localhost:3000/vendor.2fe36c3e0de211cbe176.bundle.js:7:17957)
    at h.provide.useFactory (http://localhost:3000/vendor.2fe36c3e0de211cbe176.bundle.js:7:1616)
    at e._instantiate (http://localhost:3000/vendor.2fe36c3e0de211cbe176.bundle.js:1:26592)
    at e._instantiateProvider (http://localhost:3000/vendor.2fe36c3e0de211cbe176.bundle.js:1:25339)
    at e._new (http://localhost:3000/vendor.2fe36c3e0de211cbe176.bundle.js:1:25068)

-----async gap-----
Error
    at r (http://localhost:3000/vendor.2fe36c3e0de211cbe176.bundle.js:52:7040)
    at r.fork (http://localhost:3000/vendor.2fe36c3e0de211cbe176.bundle.js:52:7966)
    at e._createInnerZone (http://localhost:3000/vendor.2fe36c3e0de211cbe176.bundle.js:7:11153)
    at new e (http://localhost:3000/vendor.2fe36c3e0de211cbe176.bundle.js:7:8661)
    at i (http://localhost:3000/vendor.2fe36c3e0de211cbe176.bundle.js:7:2020)
    at t.application (http://localhost:3000/vendor.2fe36c3e0de211cbe176.bundle.js:7:3555)
    at Object.r [as bootstrap] (http://localhost:3000/vendor.2fe36c3e0de211cbe176.bundle.js:1:1170)
    at Object.webpackJsonp.0 (http://localhost:3000/app.2fe36c3e0de211cbe176.js:1:103)
    at t (http://localhost:3000/vendor.2fe36c3e0de211cbe176.bundle.js:1:107)
    at window.webpackJsonp (http://localhost:3000/vendor.2fe36c3e0de211cbe176.bundle.js:1:384)

**Comment by SethDavenport** [comment]
`npm run dev` works fine.

The differences between these two modes are:

npm start:
* `NODE_ENV=production`
* minification
* webpack bundle generated at build time, at run time assets served by `express.static`

`npm run dev`:
* `NODE_ENV=development`
* no minification
* webpack assets served by `webpack-dev-middleware`
* nodemon

**Comment by SethDavenport** [comment]
I couldn't reproduce it initially.  But then on a hunch a blew away `node_modules` and reinstalled, now it happens.

One significant change is Angular 2 went from beta-0 to beta-1.  Investigating.

**Comment by e-schultz** [comment]
Looks like if you disable uglify - it works, with it enabled - goes wonky.

**Comment by SethDavenport** [comment]
Yeah just noticed that.  I need a combination of ng2 beta 1 and uglification to make the error happen.
